server:
  servlet:
    context-path: ""
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lims?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Xzan123321
    # schema: classpath:sql/schema.sql
    # data: classpath:sql/data.sql
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.qq.com
    username: 1647421549@qq.com
    password: jyswfzzpdsobbcdb
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  type-aliases-package: edu.scnu.lims.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.springframework.security: debug 
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
